// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC77hFutDFrqTgY-VwIydeEA0rnLaCx-Q',
    appId: '1:908749399741:web:56e17c3e482832519479d4',
    messagingSenderId: '908749399741',
    projectId: 'silvercare-84496',
    authDomain: 'silvercare-84496.firebaseapp.com',
    databaseURL: 'https://silvercare-84496-default-rtdb.firebaseio.com',
    storageBucket: 'silvercare-84496.appspot.com',
    measurementId: 'G-6VK49C9W68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsr5uDbboXqBU7IJj7u3Ddc_gNFoOO9q0',
    appId: '1:908749399741:android:64beb8f092b57e5d9479d4',
    messagingSenderId: '908749399741',
    projectId: 'silvercare-84496',
    databaseURL: 'https://silvercare-84496-default-rtdb.firebaseio.com',
    storageBucket: 'silvercare-84496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJqf_gVV_Ue2Qo74OmsLu2nPcAHx6UjY',
    appId: '1:908749399741:ios:1b1110809dc7e4389479d4',
    messagingSenderId: '908749399741',
    projectId: 'silvercare-84496',
    databaseURL: 'https://silvercare-84496-default-rtdb.firebaseio.com',
    storageBucket: 'silvercare-84496.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC77hFutDFrqTgY-VwIydeEA0rnLaCx-Q',
    appId: '1:908749399741:web:785a6ea4504582dc9479d4',
    messagingSenderId: '908749399741',
    projectId: 'silvercare-84496',
    authDomain: 'silvercare-84496.firebaseapp.com',
    databaseURL: 'https://silvercare-84496-default-rtdb.firebaseio.com',
    storageBucket: 'silvercare-84496.appspot.com',
    measurementId: 'G-MXX0GR73H0',
  );
}
